NAME = libft.a
SRC = ft_atoi.c \
	ft_isalnum.c \
	ft_isdigit.c \
	ft_memchr.c \
	ft_memmove.c \
	ft_putendl_fd.c \
	ft_split.c \
	ft_striteri.c \
	ft_strlcpy.c \
	ft_strncmp.c \
	ft_strtrim.c \
	ft_toupper.c \
	ft_bzero.c \
	ft_isalpha.c \
	ft_isprint.c \
	ft_memcmp.c \
	ft_memset.c \
	ft_putnbr_fd.c \
	ft_strchr.c \
	ft_strjoin.c \
	ft_strlen.c \
	ft_strnstr.c \
	ft_substr.c \
	ft_calloc.c \
	ft_isascii.c \
	ft_itoa.c \
	ft_memcpy.c \
	ft_putchar_fd.c \
	ft_putstr_fd.c \
	ft_strdup.c \
	ft_strlcat.c \
	ft_strmapi.c \
	ft_strrchr.c \
	ft_tolower.c 

SRCBONUS =		ft_lstsize_bonus.c \
				ft_lstnew_bonus.c \
				ft_lstmap_bonus.c \
				ft_lstlast_bonus.c \
				ft_lstiter_bonus.c \
				ft_lstclear_bonus.c \
				ft_lstadd_front_bonus.c \
				ft_lstadd_back_bonus.c \
				ft_lstdelone_bonus.c 

OBJBONUS = $(SRCBONUS:.c=.o)

INCLUDES = libft.h

OBJ = $(SRC:.c=.o)

AR = ar
ARFLAG = crs
CC = cc
CFLAGS = -Wall -Wextra -Werror -I.

all: $(NAME)

$(NAME): $(OBJ)
	$(AR) $(ARFLAG) $(NAME) $^

%.o: %.c $(INCLUDES)
	$(CC) $(CFLAGS) -c -o $@ $<

clean:
	rm -f $(OBJ) $(OBJBONUS)

fclean: clean
	rm -f $(NAME)

re: fclean all

bonus: $(OBJBONUS)
	$(AR) $(ARFLAG) $(NAME) $^
	touch bonus

$(OBJBONUS): %.o: %.c $(INCLUDES)
	$(CC) $(CFLAGS) -c -o $@ $<

.PHONY: all clean fclean re

